/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package biz.nellemann.jperf;


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import java.util.concurrent.Callable;

@Command(name = "jperf", mixinStandardHelpOptions = true, version = "0.1",
         description = "Network performance measurement tool.")
public class App implements Callable<Integer> {

    final Logger log = LoggerFactory.getLogger(App.class);

    @CommandLine.Option(names = { "-s", "--pkt-size" }, paramLabel = "SIZE", description = "datagram size")
    int packetSize = 1500;

    @CommandLine.Option(names = { "-n", "--pkt-num" }, paramLabel = "NUM", description = "datagrams to send")
    int packetCount = 100;

    @CommandLine.Option(names = { "-p", "--port" }, paramLabel = "PORT", description = "network port")
    int port = 4445;



    @Override
    public Integer call() throws Exception { // your business logic goes here...

        // Start server
        UdpServer udpServer = new UdpServer(port);
        udpServer.start();


        long sequence = 0;


        // Start client and send some messages
        UdpClient udpClient = new UdpClient("localhost", port);

        // Start datagram
        Datagram datagram = new Datagram(DataType.HANDSHAKE.getValue(), packetSize, sequence++);
        udpClient.send(datagram);
        Thread.sleep(100);

        // TODO: Wait for ACK
        datagram = udpClient.receive();
        if(datagram.getType() != DataType.ACK.getValue()) {
            log.warn("No ACK!");
            return -1;
        }


        // Data datagrams ...
        for(int i = 0; i < packetCount; i++) {
            datagram = new Datagram(DataType.DATA.getValue(), packetSize, sequence++);
            udpClient.send(datagram);
            //Thread.sleep(50);
        }

        // End datagram
        Thread.sleep(500);
        datagram = new Datagram(DataType.END.getValue(), packetSize, sequence++);
        udpClient.send(datagram);

        udpClient.close();
        Thread.sleep(1500);

        return 0;
    }

    // this example implements Callable, so parsing, error handling and handling user
    // requests for usage help or version help can be done with one line of code.
    public static void main(String... args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }

}
